### A Pluto.jl notebook ###
# v0.19.30

using Markdown
using InteractiveUtils

# ╔═╡ a181d512-c413-11ee-0833-c545e1f2c2ca
begin
    using Pkg
	NOTEBOOKS_PATH = "src/pluto_notebooks"
	DATA_PATH = "data"  # store generated by notebook data
    @assert endswith(pwd(), NOTEBOOKS_PATH) "Wrong directory!"
	RDR_PATH = "../.."  # path to the RDR project root
    Pkg.activate(RDR_PATH)
	
	import RansacDoneRight as RDR
    md"""
    ### Activating RansacDoneRight environment...
    """
end

# ╔═╡ dcf1c212-c92b-4db2-bdf1-c794ec304a70
begin
	using StaticArrays
	using Revise
end

# ╔═╡ 667c21e9-92be-465d-b627-274dde13e3f5
html"""
<style>
	main {
		margin: 0 auto;
		max-width: 2000px;
		padding-left: max(160px, 15%);
		padding-right: max(160px, 15%);
	}
</style>
"""

# ╔═╡ 29130995-cdda-4020-a52a-338218f8f9e2
l = RDR.find_uncertain_line_from_two_points(
    RDR.UncertainPoint(
        SVector(9.0, 10.0, 1.0),
        0.2 * [2.5 0.5 0;
            0.5 1 0;
            0 0 0
        ]
    ),
    RDR.UncertainPoint(
        SVector(20.0, 22.0, 1.0),
        0.2 * [3 1.5 0;
            1.5 2 0;
            0 0 0
        ]
    ))

# ╔═╡ 7bc1eb75-fe7f-4778-b730-035569f5526e
RDR.plot_confidence_region(l, 0.4, 5:0.1:25, 5:0.1:25)

# ╔═╡ Cell order:
# ╟─667c21e9-92be-465d-b627-274dde13e3f5
# ╟─a181d512-c413-11ee-0833-c545e1f2c2ca
# ╠═dcf1c212-c92b-4db2-bdf1-c794ec304a70
# ╠═29130995-cdda-4020-a52a-338218f8f9e2
# ╠═7bc1eb75-fe7f-4778-b730-035569f5526e
